CREATE DATABASE ILLIDAN_DB
GO
USE ILLIDAN_DB


CREATE TABLE TB_ILN_PERSONAGEM(
	ID_PERSONAGEM INT IDENTITY(1,1) PRIMARY KEY ,
	DS_PERSONAGEM VARCHAR(150) NOT NULL,
    DS_URL_IMG VARCHAR(MAX)
);

CREATE TABLE TB_ILN_USUARIOS(
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    DS_NOME VARCHAR (150) NOT NULL,
    DS_LOGIN VARCHAR (50) NOT NULL,
    DS_SENHA VARCHAR (100) NOT NULL,
    FL_STATUS BIT DEFAULT 1,
    ID_PERSONAGEM INT NOT NULL
	CONSTRAINT FK_PERSONAGEM FOREIGN KEY (ID_PERSONAGEM) 
	REFERENCES TB_ILN_PERSONAGEM (ID_PERSONAGEM)
);
